RACK_ENV                  = ENV['RACK_ENV']
GOODREADS_KEY             = ENV['GOODREADS_KEY']
GOODREADS_SECRET          = ENV['GOODREADS_SECRET']
ROTTENTOMATOES_API_KEY    = ENV['ROTTENTOMATOES_API_KEY']
SENDGRID_USERNAME         = ENV['SENDGRID_USERNAME']
SENDGRID_PASSWORD         = ENV['SENDGRID_PASSWORD']
SENDGRID_SUBJECT          = ENV['SENDGRID_SUBJECT']
SENDGRID_FROM             = ENV['SENDGRID_FROM']

case RACK_ENV
when "production"
else  
  # defined above 
end
